name: Tosca Test
on: [push]
jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:    
      - name: get accesstoken
        run: |
          curl --location --request POST 'https://fhbgld.oktapreview.com/oauth2/default/v1/token' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --header 'Cookie: JSESSIONID=5D9B4CFA4A71FA9459625E8B481AC9D5' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode 'client_id=E2G_Agents' \
          --data-urlencode 'client_secret=${{ secrets.CLIENT_SECRET }}' \
          --data-urlencode 'scope=E2GApi' \
          -o response.json

      - name: save access token on env var
        run: echo "ACCESS_TOKEN=$(cat response.json | jq -r .access_token)" >> $GITHUB_ENV

      - name: trigger test on agent
        run: |
          curl --location --request POST 'https://fhbgld.my.tricentis.com/default/_e2g/api/flowExecutions' \
          --header 'Content-Type: application/json' \
          --header 'X-Tricentis: OK' \
          --header 'Accept-Language: de' \
          --header 'Authorization: Bearer ${{env.ACCESS_TOKEN}}' \
          --data-raw '{
            "flowId": "a2871bf8-b3c0-43cd-bacd-97cedf769cf8",
            "timeoutInMinutes": 300
          }'